service: daily-tweet
provider:
  name: aws
  runtime: rust
  environment:
    SEINBOT_CONSUMER_KEY: ${file(twitter-secrets.json):consumer_key}
    SEINBOT_CONSUMER_SECRET: ${file(twitter-secrets.json):consumer_secret}
    SEINBOT_ACCESS_KEY: ${file(twitter-secrets.json):access_key}
    SEINBOT_ACCESS_SECRET: ${file(twitter-secrets.json):access_secret}
    RUST_BACKTRACE: 1
plugins:
  - serverless-rust
package:
  individually: true
functions:
  seinbot:
    handler: seinbot-rs
    events:
      - schedule: rate(24 hours)
